---
processes:
- name: cf-containers-broker
  executable: /var/vcap/jobs/cf-containers-broker/bin/ctl.sh
  args: []
  ephemeral_disk: true
  persistent_disk: false
  env:
    PORT: <%= p("port") %>
    DOCKER_URL: <%= p("docker_url") %>

  limits:
    memory: 256M
    open_files: 1024
  additional_volumes:
  - path: /var/vcap/data/sys/run/docker
