production:
  auth_username: <%= p('username') %>
  auth_password: <%= p('password') %>
  cookie_secret: <%= p('cookie_secret') %>
  session_expiry: <%= p('session_expiry') %>

  cc_api_uri: <%= p('cf.api_url', 'https://api.unknown.cloudfoundry') %>
  external_host: <%= p('external_host', spec.address) %>
  external_ip: <%= p('external_ip', spec.address) %>

  ssl_enabled: <%= p('ssl_enabled') %>
  skip_ssl_validation: <%= p('skip_ssl_validation') %>

  host_directory: /var/vcap/store/cf-containers-broker/
  max_containers: <%= p('max_containers') %>
  allocate_docker_host_ports: <%= p('allocate_docker_host_ports') %>
  enable_host_port_envvar: <%= p('enable_host_port_envvar') %>

  container_env_var_dir: '/var/vcap/store/cf-containers-broker/envdir'
  log_path: '/var/vcap/sys/log/cf-containers-broker/cf-containers-broker.log'

  services: <%= JSON.pretty_generate(p('services')) %>
