- path: /releases/name=cf-containers-broker/url
  type: replace
  value: "https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/cf-containers-broker-1.0.2-ubuntu-trusty-3541.10-20180405-081322-395132208-20180405081325.tgz"
- path: /releases/name=cf-containers-broker/version
  type: replace
  value: "1.0.2"
- path: /releases/name=cf-containers-broker/sha1
  type: replace
  value: "c949f05f46ab290f6813fd140e7c8cea9ac5d08a"

- path: /releases/name=cf-containers-broker/stemcell?
  type: replace
  value:
    os: "ubuntu-trusty"
    version: "3541.10"
