- path: /releases/name=cf-containers-broker/url
  type: replace
  value: "https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/cf-containers-broker-1.0.1-ubuntu-trusty-3541.10-20180330-233820-702173059-20180330233825.tgz"
- path: /releases/name=cf-containers-broker/version
  type: replace
  value: "1.0.1"
- path: /releases/name=cf-containers-broker/sha1
  type: replace
  value: "258ef1276bd18fcc6c5609951f623253bccec5e9"

- path: /releases/name=cf-containers-broker/stemcell?
  type: replace
  value:
    os: "ubuntu-trusty"
    version: "3541.10"
