---
name: docker-broker

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway
    consumes:
      backend:
        from: backend
    provides:
      subway:
        as: broker
        shared: true
    properties:
      username: broker
      password: ((subway-broker-password))
      name: docker-broker

- name: docker
  azs: [z1,z2,z3]
  instances: 1
  persistent_disk: 65536
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

  - name: cf-containers-broker
    release: cf-containers-broker
    provides:
      cf-containers-broker:
        as: backend
        shared: true
    properties:
      username: broker
      password: ((docker-broker-password))
      cookie_secret: ((docker-broker-cookie-secret))
      max_containers: 20
      fetch_images: true
      services: []

- name: sanity-test
  azs: [z1]
  lifecycle: errand
  instances: 1
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: sanity-test-broker
    release: cf-containers-broker
    consumes:
      servicebroker:
        from: broker
      docker-broker-catalog:
        from: backend
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

variables:
- name: subway-broker-password
  type: password
- name: docker-broker-password
  type: password
- name: docker-broker-cookie-secret
  type: password
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.2.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: cf-subway
  version: 3.2.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/cf-subway-boshrelease?v=3.2.0
  sha1: 57de13d5a7b4709c065b6f909cd86372badfe2da
- name: docker
  version: 31.0.0
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v31.0.0/docker-31.0.0.tgz
  sha1: 5d7e9052297b26ad4337b4d539ba702cccb20080
- name: cf-containers-broker
  version: 1.0.0
  url: https://github.com/cloudfoundry-community/cf-containers-broker-boshrelease/releases/download/v1.0.0/cf-containers-broker-1.0.0.tgz
  sha1: f325ecc4160bde784f9cb48c9d2b32d16de333c3
